version: "3"

services:
  database:
    image: 'mongo:4.2'
    container_name: 'database'
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo-volume:/data/db
    networks:
      - inventory_control_networks
    ports:
      - '27017:27017'

networks:
  inventory_control_networks:
    driver: bridge